name: "Close Nexus Staging Repository"
description: "Closes a staging Nexus repository."
author: TheMrMilchmann
inputs:
  username:
    description: 'The username to use to authenticate against the Nexus.'
    required: true
  password:
    description: 'The password to use to authenticate against the Nexus.'
    required: true
  base-url:
    description: 'The base URL of the Nexus instance.'
    required: true
    default: 'https://oss.sonatype.org/'
  staging-repository-id:
    description: 'The ID of the staging repository.'
    required: true
  description:
    description: 'An optional description for the closed repository.'
    required: false
    default: 'Closed by GitHub Actions'
  transition-timeout:
    description: 'The maximum time (in minutes) to wait for the repository to transition.'
    required: true
    default: '5'
runs:
  using: node16
  main: '../dist/close-staging-repo/index.js'
branding:
  icon: lock
  color: green