name: "Release Nexus Staging Repository"
description: "Releases a staging Nexus repository."
author: TheMrMilchmann
inputs:
  username:
    description: 'The username to use to authenticate against the Nexus.'
    required: true
  password:
    description: 'The password to use to authenticate against the Nexus.'
    required: true
  base-url:
    description: 'The base URL of the Nexus instance.'
    required: true
    default: 'https://oss.sonatype.org/'
  staging-repository-id:
    description: 'The ID of the staging repository.'
    required: true
  description:
    description: 'An optional description for the promoted repository.'
    required: false
    default: 'Released by GitHub Actions'
  auto-drop:
    description: 'Whether to automatically drop the repository.'
    required: true
    default: 'true'
runs:
  using: node16
  main: '../dist/release-staging-repo/index.js'
branding:
  icon: upload
  color: green